version: '3.8'

services:
  service1:
    build:
      dockerfile: Dockerfile_1
    environment:
      HOST: ${HOST}
      MASTER_KEY: ${MASTER_KEY}
      DATABASE_ID: ${DATABASE_ID}
      CONTAINER_ID: ${CONTAINER_ID}
      OPENAI_API_BASE: ${OPENAI_API_BASE}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_LLM_MODEL: ${OPENAI_LLM_MODEL}
      OPENAI_EMBEDDING_MODEL: ${OPENAI_EMBEDDING_MODEL}
      OPENAI_API_VERSION: ${OPENAI_API_VERSION}
      AZURE_SEARCH_SERVICE_ENDPOINT: ${AZURE_SEARCH_SERVICE_ENDPOINT}
      AZURE_SEARCH_INDEX_NAME: ${AZURE_SEARCH_INDEX_NAME}
      AZURE_SEARCH_INDEX_KEY: ${AZURE_SEARCH_INDEX_KEY}
    ports : 
          - "8501:8501"
  
  service2:
    build:
      dockerfile: Dockerfile_2
    environment:
        HOST: ${HOST}
        MASTER_KEY: ${MASTER_KEY}
        DATABASE_ID: ${DATABASE_ID}
        CONTAINER_ID: ${CONTAINER_ID}
        OPENAI_API_BASE: ${OPENAI_API_BASE}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        OPENAI_LLM_MODEL: ${OPENAI_LLM_MODEL}
        OPENAI_EMBEDDING_MODEL: ${OPENAI_EMBEDDING_MODEL}
        OPENAI_API_VERSION: ${OPENAI_API_VERSION}
        AZURE_SEARCH_SERVICE_ENDPOINT: ${AZURE_SEARCH_SERVICE_ENDPOINT}
        AZURE_SEARCH_INDEX_NAME: ${AZURE_SEARCH_INDEX_NAME}
        AZURE_SEARCH_INDEX_KEY: ${AZURE_SEARCH_INDEX_KEY}
  
  service3:
    build:
      dockerfile: Dockerfile_3
    environment:
        HOST: ${HOST}
        MASTER_KEY: ${MASTER_KEY}
        DATABASE_ID: ${DATABASE_ID}
        CONTAINER_ID: ${CONTAINER_ID}
        OPENAI_API_BASE: ${OPENAI_API_BASE}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        OPENAI_LLM_MODEL: ${OPENAI_LLM_MODEL}
        OPENAI_EMBEDDING_MODEL: ${OPENAI_EMBEDDING_MODEL}
        OPENAI_API_VERSION: ${OPENAI_API_VERSION}
        AZURE_SEARCH_SERVICE_ENDPOINT: ${AZURE_SEARCH_SERVICE_ENDPOINT}
        AZURE_SEARCH_INDEX_NAME: ${AZURE_SEARCH_INDEX_NAME}
        AZURE_SEARCH_INDEX_KEY: ${AZURE_SEARCH_INDEX_KEY}
