FROM python:3.10-slim

# Set the working directory
WORKDIR /app

COPY . .

RUN pip install --upgrade pip

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt


# Expose the Streamlit port
EXPOSE 8501

# CMD to start Streamlit and cron services
CMD streamlit run app.py
